from Animator import Animator
from MOOSEXML import readMOOSEXML

wells_data = readMOOSEXML('wells.xml')
fracs_data = readMOOSEXML('fracs.xml')

# ani = Animator(2, 2)
# ani.nextSubplot('$z$', 'Pressure')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['p_liquid'], '$p_\\ell$')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['p_vapor'], '$p_v$')
# ani.nextSubplot('$z$', 'Velocity')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['vel_liquid'], '$u_\\ell$')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['vel_vapor'], '$u_v$')
# ani.nextSubplot('$z$', 'Void Fraction', pad=True)
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['alpha_vapor'], '$\\alpha_v$')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['alpha_vapor_base'], '$\\alpha_v^{wick,i,0}$')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['alpha_vapor_max_i'], '$\\alpha_v^{wick,i,+}$')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['alpha_vapor_max_o'], '$\\alpha_v^{wick,o,+}$')
# ani.nextSubplot('$z$', 'Temperature')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['T_liquid'], '$T_\\ell$')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['T_vapor'], '$T_v$')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['T_int'], '$T_{int}$')
# ani.addSet(data['mat_props_vpp']['x'], data['mat_props_vpp']['T_wall'], '$T_{wall}$')
# ani.show()
ani = Animator(2, 2)
ani.nextSubplot('$z$', 'Pressure')
ani.addSet(wells_data['p_inj_1']['z'], wells_data['p_inj_1']['p'], 'Injection 1')
ani.addSet(wells_data['p_inj_2']['z'], wells_data['p_inj_2']['p'], 'Injection 2')
ani.addSet(wells_data['p_ext_1']['z'], wells_data['p_ext_1']['p'], 'Extraction 1')
ani.addSet(wells_data['p_ext_2']['z'], wells_data['p_ext_2']['p'], 'Extraction 2')
ani.addSet(fracs_data['p_frac1']['z'], fracs_data['p_frac1']['p'], 'Fracture 1')
ani.nextSubplot('$z$', 'Mass Flow Rate')
ani.addSet(wells_data['flux_inj_1']['z'], wells_data['flux_inj_1']['mass_flux'], 'Injection 1')
ani.addSet(wells_data['flux_inj_2']['z'], wells_data['flux_inj_2']['mass_flux'], 'Injection 2')
ani.addSet(wells_data['flux_ext_1']['z'], wells_data['flux_ext_1']['mass_flux'], 'Extraction 1')
ani.addSet(wells_data['flux_ext_2']['z'], wells_data['flux_ext_2']['mass_flux'], 'Extraction 2')
ani.addSet(fracs_data['flux_frac1']['z'], fracs_data['flux_frac1']['mass_flux'], 'Fracture 1')
ani.nextSubplot('$x$', 'Pressure')
ani.addSet(wells_data['p_inj_1']['x'], wells_data['p_inj_1']['p'], 'Injection 1')
ani.addSet(wells_data['p_inj_2']['x'], wells_data['p_inj_2']['p'], 'Injection 2')
ani.addSet(wells_data['p_ext_1']['x'], wells_data['p_ext_1']['p'], 'Extraction 1')
ani.addSet(wells_data['p_ext_2']['x'], wells_data['p_ext_2']['p'], 'Extraction 2')
ani.addSet(fracs_data['p_frac1']['x'], fracs_data['p_frac1']['p'], 'Fracture 1')
ani.nextSubplot('$x$', 'Mass Flow Rate')
ani.addSet(wells_data['flux_inj_1']['x'], wells_data['flux_inj_1']['mass_flux'], 'Injection 1')
ani.addSet(wells_data['flux_inj_2']['x'], wells_data['flux_inj_2']['mass_flux'], 'Injection 2')
ani.addSet(wells_data['flux_ext_1']['x'], wells_data['flux_ext_1']['mass_flux'], 'Extraction 1')
ani.addSet(wells_data['flux_ext_2']['x'], wells_data['flux_ext_2']['mass_flux'], 'Extraction 2')
ani.addSet(fracs_data['flux_frac1']['x'], fracs_data['flux_frac1']['mass_flux'], 'Fracture 1')
ani.show()
